### PR TITLE
To do list - Peer feedback

### PR DESCRIPTION
**Pull request by ReshyResh**
This PR is for fixing drag and drop issues and receiving peer to peer feedback about JS best practices.

### CODE REVIEW

**Comment by isaka-lumato** [comment]
you have done a great job on this project
but.

- [ ] it would be much better if you used restructuring on your sort function, it would have made your code much cleaner and much smaller.

**Comment by ReshyResh** [comment]
# Hello @isaka-lumato !
I changed the code in the swap function to make it work using ES6 destructuring, as you can see in the latest commit.




I think the pull request is ready for deployment, let me know if there is any other requested changes!

**Comment by isaka-lumato** [comment]
# Hello @ReshyResh!
# CONGRATULATIONS 👋
congrats

You've done a great job on the project, following all the required best practices in your code.

  - ✔ Your variable names are meaningful and understandable.
  - ✔ You are not repeating yourself with for loops.
  - ✔ You are using correct ES6 syntax.

### Good job, time to merge it! 🎉

**Comment by ReshyResh** [comment]
## Testing
Added functions for testing the add/remove functions.
Run `npm run test` for testing. 
Expected output:

**Review by Emmyn5600 — APPROVED** [review]
Hi, 

Good job so far! 👏🏼 @ReshyResh  

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Testing for Add/Remove functions are passing successfully.:heavy_check_mark:
testing


## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the project requirements.
 
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Pull request merged**
